# Generated by Django 4.2.3 on 2024-10-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foot', '0002_footstepdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootfallData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=255)),
                ('footsteps', models.IntegerField()),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('dwell_time', models.FloatField()),
            ],
        ),
    ]
